/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package watchtour;
import java.sql.*;
import java.awt.*;
/**
 *
 * @author Muneeb
 */
public class MovieCard extends javax.swing.JPanel {

    /**
     * Creates new form MovieCard
     */
    private int id;
    private String mail;
    
    public MovieCard(int id, String mail) {
        this.id = id;
        this.mail = mail;
        initComponents();
        like.setForeground(Color.WHITE);
        like.setBackground(Color.BLACK);
        dislike.setForeground(Color.WHITE);
        dislike.setBackground(Color.BLACK);
        plot.setLineWrap(true);
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");  
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","muneeb");  
            PreparedStatement pstmt = con.prepareStatement("select * from movies where id = ?");
            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){
                movieName.setText(rs.getString(2));
                genre.setText(rs.getString(3));
                rating.setText(rs.getString(4));
                year.setText(rs.getString(5));
                plot.setText(rs.getString(6));
            }
            con.close(); 
        }catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieName = new javax.swing.JLabel();
        genre = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        like = new javax.swing.JButton();
        dislike = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        plot = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        movieName.setText("MovieName");

        genre.setText("Genre");

        rating.setText("Rating");

        year.setText("Year");

        like.setText("LIKE");
        like.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeActionPerformed(evt);
            }
        });

        dislike.setText("DISLIKE");
        dislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dislikeActionPerformed(evt);
            }
        });

        plot.setColumns(20);
        plot.setRows(5);
        plot.setText("plot");
        jScrollPane1.setViewportView(plot);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(like)
                                .addGap(88, 88, 88)
                                .addComponent(dislike))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(movieName)
                                .addGap(57, 57, 57)
                                .addComponent(rating)
                                .addGap(54, 54, 54)
                                .addComponent(genre)
                                .addGap(18, 18, 18)
                                .addComponent(year)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieName)
                    .addComponent(rating)
                    .addComponent(genre)
                    .addComponent(year))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(like)
                    .addComponent(dislike))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void likeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeActionPerformed
        like.setEnabled(false);
        dislike.setEnabled(true);
        like.setBackground(Color.GREEN);
        dislike.setBackground(Color.BLACK);
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","muneeb");
            PreparedStatement pstmt = con.prepareStatement("select genre from movies where id = ?");
            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();
            String movieGenre = "";
            while(rs.next()) {
                movieGenre = rs.getString(1);
            }
            pstmt = con.prepareStatement("insert into user_genres values(?, ?)");
            pstmt.setString(1, mail);
            pstmt.setString(2, movieGenre);
            pstmt.executeUpdate();
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_likeActionPerformed

    private void dislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dislikeActionPerformed
        like.setEnabled(true);
        dislike.setEnabled(false);
        dislike.setBackground(Color.RED);
        like.setBackground(Color.BLACK);
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","muneeb");
            PreparedStatement pstmt = con.prepareStatement("select genre from movies where id = ?");
            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();
            String movieGenre = "";
            while(rs.next()) {
                movieGenre = rs.getString(1);
            }
            pstmt = con.prepareStatement("select * from user_genres where email = ? and liked_genre = ?");
            pstmt.setString(1, mail);
            pstmt.setString(2, movieGenre);
            rs = pstmt.executeQuery();
            if(rs.next()){
                pstmt = con.prepareStatement("delete from user_genres where email = ? and liked_genre = ?");
                pstmt.setString(1, mail);
                pstmt.setString(2, movieGenre);
                pstmt.executeUpdate();
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_dislikeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dislike;
    private javax.swing.JLabel genre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton like;
    private javax.swing.JLabel movieName;
    private javax.swing.JTextArea plot;
    private javax.swing.JLabel rating;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
